### ISSUE TITLE
关于使用问题

### ISSUE THREAD

**Issue by Wzhrdx** [miiiku/hexo-theme-flexblock#14]
1. 怎么在阅读界面添加滚动条，现在的博客内容稍微一长，鼠标滚动就非常难受
2.怎么在阅读界面的右边添加作者栏目，下面可以放目录什么的
3.关于ins的界面应该如何设置
我是一个hexo的小白，很喜欢你的这个主题，希望你可以帮我解决这个问题

**Comment by miiiku** [comment]
第一个问题可以在主题文件下flex-block/source/css/style.styl 第9行注释掉就ok [flex-block/source/css/style.styl](https://github.com/miiiku/flex-block/blob/ae5fa226829c6201e53cce7cfaf049a33c875007/source/css/style.styl#L9)

第二个问题目前是不支持的，不过最近在改版，下个版本可能会加入。

第三个ins界面是我自己的一个小模块，由于私人集成比较高，目前不打算加入主题文件中，如果你有前端基础，可以fork我的[hexo-blog](https://github.com/miiiku/hexo-blog)这个项目来修改。
