### ISSUE TITLE
界面底部褪色

### ISSUE THREAD

**Issue by Wzhrdx** [miiiku/hexo-theme-flexblock#18]
![image](https://user-images.githubusercontent.com/62975285/94992188-d1644f00-05ba-11eb-8adf-9b7e051f6830.png)
所有节目的底部的颜色全部消失了，是不是渲染不正常

**Comment by seeleclover** [comment]
原本不就是这个颜色的吗？

**Comment by Wzhrdx** [comment]
原来底部不应该是彩色的吗，我记得是粉色的

**Comment by seeleclover** [comment]
那个粉色是主题作者自己自定义的颜色。
如果你想更改这里的颜色，请找到这个文件：**_<当前Hexo站点的文件夹>\themes\flex-block\source\css\_partial\footer.styl_**
找到这一部分：
```
/*第5-20行*/
.footer-container {
    margin: auto
    width: 100%
    max-width: max-content-width
    text-align: center
    color: #aeb5be

    p {
      line-height: 2
    }

    a {
      color: #161b3d
      font-weight: bolder
    }
}
```
修改a标签中color的值即可（原作者用的是 color: var(--theme-link-color); ）

**Comment by seeleclover** [comment]
close #18
