### ISSUE TITLE
你好，我可以移植一下你的主题吗?

### ISSUE THREAD

**Issue by Guiyunweb** [miiiku/hexo-theme-flexblock#24]
你好，我特别喜欢你的主题，但因为我使用的博客框架不是**Hexo**，所以想移植一下你的主题，到我使用的**Halo**这个博客框架下，请问可以吗？

**Comment by Guiyunweb** [comment]
以前在你的博客的留言版留言过，但是一直得到回信，我就擅自将1.0的博客移植过去了(这里没有得到你的同意就移植了，实在对不起了)
现在觉得觉得2.0版本也很不错，所以想将2.0版也移植过去，所以想到在github上提一个issues，得到你的同意

**Comment by miiiku** [comment]
当然可以啦，谢谢你的喜欢~ 😊
