### ISSUE TITLE
首页baner图无法显示

### ISSUE THREAD

**Issue by shenghansen** [miiiku/hexo-theme-flexblock#25]
已经绑定了baner图的url了，用的是腾讯云的图床，但是就是无法显示，我F12一看没有post-image的div，不知道什么原因
![image](https://user-images.githubusercontent.com/56721884/126381296-b73e17cc-f857-47c1-9c9d-37eac9e7b948.png)

**Comment by miiiku** [comment]
首先是你banner的单词打错了，这个banner图指定的的首页进入上面的那张大图，并不是文章卡片的背景图。

如果你要设置文章卡片的背景图，请在文章MD文件中顶部加入cover: 你的图片地址

见: [https://kyori.xyz/2021/07/081100.html](https://kyori.xyz/2021/07/081100.html)
