### ISSUE TITLE
关于页面的cover，categories类型页面和页面渲染

### ISSUE THREAD

**Issue by dangjinghao** [miiiku/hexo-theme-flexblock#26]
- 建议相对链接的cover修改为绝对链接，原因是根据官方教程在开启post_asset_folder后，使用相对链接会导致上一个帖子/下一个帖子和主页显示时候帖子的cover错误。例如我在一篇名为“22”的文章中写cover: ./33.jpg，在本文章中是可以正常读取为/22/33.jpg，但是主页，其他帖子的newer,elder的显示是不正常的，我只能直接关闭post_asset_folder来解决。

- 将page的type修改为categories后,cover不能正常使用，只有在/categories/index.html才会正常显示这个cover，例如进入/categories/doc/显示的还是主页banner图。

- 在为page添加type: categories后生成的页面，/categories/index.html并不像分类页面而是一个普通文章。（装了hexo-generator-category 后也没有解决，是我想多了），这两个问题似乎都是由于本主题没有默认生成tag和categories收集页面但是帖子可以默认使用标签分类导致的，我不知道如何解决。

- md的代码（即`这个`）网页上渲染出来可读性似乎不太好，就我来说，它的白色阴影会导致看到第一眼时候可读性下降，希望能优化？

- 主页各文章的banner更应该使用文章中引用的banner的略缩图来节省流量？比如分辨率降低到0.5，毕竟主页图片并不大，过大的图可能不会产生更多效果还会导致流量增多。（当然这个可以站长自主优化）

**Comment by dangjinghao** [comment]
另：在`https://kyori.xyz/links`中`hexo new links`应修改为`hexo new page links`，new links默认生成名为links的帖子

**Comment by dangjinghao** [comment]
另另：是否应该将主题config.yml中的部分与博客信息有关的配置项（如menu,banner,notice,auther,beian,数据分析这些不修改主题本身的配置）移动到_data文件夹中以增加其作用？
暂时发现_data除了写友链的其他作用

**Comment by dangjinghao** [comment]
另另另：中国备案网站网址已修改，[https://beian.miit.gov.cn](https://beian.miit.gov.cn)这是新网址

**Comment by miiiku** [comment]
内容有点多 😂

### cover问题：

因为在`Front-matter`中无法使用md的标签，所以hexo中提供的`asset_img `等标签插件无用，有考虑过使用文章路径加封面相对路径拼接成一个绝对路径，但是如果在文章链接格式后缀为`.html`时，会出现问题，所以目前如果要使用本地资产文件，建议自己手动拼接完整路径。

如你有一篇文章叫test.md，那么你在cover填写的路径应为:

` [你的站点地址 || _config.url]/[_config.permalink]/[图片名称]`

### categories问题:

在`1.0`版本中，就已经删除`categories`和`tags`的单独页面，详见: [https://github.com/miiiku/hexo-theme-flexblock/tree/v1.0#202007](https://github.com/miiiku/hexo-theme-flexblock/tree/v1.0#202007)

### 代码片段样式:

优化了一下文字阴影的问题，看着不刺眼了。

### banner压缩：

目前hexo不支持本地压缩，最好的解决方案还是交给CDN提供商处理。

**`new links`的文案已经修改，确实是一个错误的命令。**

**备案网站地址已更新到最新的。**

最后：

至于吧站点的属性放到`data`中，这个目前不打算更改，后期也许会采用这种方案，目前这种吧站点的`属性`放在config配置文件中我觉得没有什么不妥，`menu`，`banner`，`auther`这些都是站点属性，它不应该被当成数据，当然这个仁者见仁，都有自己的理解～
