### ISSUE TITLE
如何开启 LaTeX

### ISSUE THREAD

**Issue by CGHeavenHealer** [miiiku/hexo-theme-flexblock#27]
RT

**Comment by miiiku** [comment]
目前没有内置LaTex公式哦，需要自己接入插件，hexo是有现成的插件的，你可以找一下，也可以参考[https://github.com/miiiku/hexo-theme-flexblock/issues/16](https://github.com/miiiku/hexo-theme-flexblock/issues/16)

**Comment by CGHeavenHealer** [comment]
解决了，谢谢！
