### ISSUE TITLE
友链相关问题

### ISSUE THREAD

**Issue by dangjinghao** [miiiku/hexo-theme-flexblock#29]
links.yml中的description和avatar填写后无法生成对应页面内容

**Comment by miiiku** [comment]
这是一个bug，周一修复，原因是在ejs模板中取错字段了，详见[https://github.com/miiiku/hexo-theme-flexblock/blob/master/layout/_partial/page.ejs#L17](https://github.com/miiiku/hexo-theme-flexblock/blob/master/layout/_partial/page.ejs#L17)

你可以在links.yml中复制一份`description`改为`describe`，复制一份`avatar`改为`cover`，当然你也可以直接改源码
