### ISSUE TITLE
toc问题相关

### ISSUE THREAD

**Issue by dangjinghao** [miiiku/hexo-theme-flexblock#31]
md写法`[toc]`无法被转换
在front-matter设置开启的toc似乎存在只能显示部分目录的bug
这是演示 可以发现h1和h4h5h6无法正常显示
https://blog.gugugu.cloud/2021/08/20/toc-demo/
（演示页面以后会删除）

**Comment by miiiku** [comment]
这不是BUG，是设置问题，默认生成h2 h3

具体配置地方在[https://github.com/miiiku/hexo-theme-flexblock/blob/master/_config.yml#L19](https://github.com/miiiku/hexo-theme-flexblock/blob/master/_config.yml#L19)

使用的是HEXO的辅助函数来完成，详见[https://hexo.io/zh-cn/docs/helpers#toc](https://hexo.io/zh-cn/docs/helpers#toc)
