### ISSUE TITLE
关于代码高亮的问题

### ISSUE THREAD

**Issue by Jy-stdio** [miiiku/hexo-theme-flexblock#32]
我在hexo配置文件中打开了高亮，但是代码并没有高亮，请问有解决办法嘛

**Comment by miiiku** [comment]
能贴一下你的书写代码或者配置项什么的吗，这样我也不知道是啥问题

**Comment by miiiku** [comment]
可以看一下这个实例配置项 是能正常代码高亮的[https://github.com/miiiku/flexblock-example-site](https://github.com/miiiku/flexblock-example-site)
