### ISSUE TITLE
valine.js的引用问题

### ISSUE THREAD

**Issue by Healock** [miiiku/hexo-theme-flexblock#36]
因为想修改Valine的样式，所以得单独拎一个Valine的js出来，就是不太清楚这个路径该在哪里配置

**Comment by miiiku** [comment]
可以看下这个文件[https://github.com/miiiku/hexo-theme-flexblock/blob/master/layout/_widget/comment.ejs](https://github.com/miiiku/hexo-theme-flexblock/blob/master/layout/_widget/comment.ejs)

或者在[https://github.com/miiiku/hexo-theme-flexblock/blob/master/layout/_partial/footer-other.ejs](https://github.com/miiiku/hexo-theme-flexblock/blob/master/layout/_partial/footer-other.ejs)这个文件里添加自定义代码
