### ISSUE TITLE
希望支持LaTeX表达式

### ISSUE THREAD

**Issue by zaiic** [miiiku/hexo-theme-flexblock#40]
![image](https://user-images.githubusercontent.com/61856080/142019237-cb76417f-edaa-40f7-b298-6e81c4015a9f.png)
想在blog上面分享一些数学公式，但是发现不支持LaTeX....

**Comment by seeleclover** [comment]
目前作者没有内置LaTex公式，需要自己接入插件，hexo是有现成的插件的，你可以找一下，也可以参考https://github.com/miiiku/hexo-theme-flexblock/issues/16
