### ISSUE TITLE
请问单个文章的封面图片是如何设置

### ISSUE THREAD

**Issue by neko205-mx** [miiiku/hexo-theme-flexblock#49]
并没有看到相关的说明。。。或许是我眼瞎（）
![Uploading 屏幕截图 2022-07-12 000706.png…]()

**Comment by miiiku** [comment]
在md文件中的front-matter中设置cover字段即可；

https://kyori.xyz/2021/07/081100.html

**Comment by neko205-mx** [comment]
谢谢 解决了
刚从wp转过来真的有点不适应）
