### ISSUE TITLE
文章阅读体验的几点意见

### ISSUE THREAD

**Issue by SteinsGate-zero** [miiiku/hexo-theme-flexblock#5]
大佬很喜欢您的博客设计，我非常想使用它。我本人经常更新一些体系化的教程文章，所以对阅读体验方面稍有些敏感。我观察到您的主题对于文章内容的阅读体验上我觉得还可以进行一些优化，目前的阅读体验有点难受、尤其是教程类。

说个提升阅读体验的几个建议：
1.如果文章内容采用了分级标题语法，在进入文章后，文章向右或者向左偏移整个内容，剩下的一部分页面，显示导航目录树，方便阅读学习（最想要的功能）
2.进入文章页面后，文章页面显示的宽度可以稍微改窄一些，太宽如果文字多有点阅读疲劳。（没有也可以）
3.给显示的文章内容加个阴影框，可以让文章页面看起来更有可视性。（没有也可以）
可以参考的这个模板的布局例子我说的三点都做到了：https://jerryc.me/posts/20bbe8ff/#%E5%89%8D%E8%A8%80

2与3建议的核心思路是，人在阅读特定区域时，大脑会只让你看清楚你要看的区域，在视觉边界的内容就会进行动态模糊处理，所以缩窄有益于提升阅读的信息密度。而因为信息密度的增加，阅读效率（速度）也会得到提升。
例如：现在的博客文章没有缩小处理，所以在阅读的时候需要一定的左右摇头，这是不必要的。如果缩小内容，通过严谨的移动就能完成文章的阅读，所以能本质的提升效率。
另一点就是给文章内容加上边框阴影后，等于给大脑了一个信息“你要阅读的内容是在这个框里的”这种暗示也会提高学习效率。

因为没有上述我觉得很必要的阅读体验，所以目前这个主题的文章点进去，会有一定的不知所措的感觉，再加上导航树之类的缺失，我难以进行多个文章的阅读。但是网站的主页，图片显示的这些设计我真的非常非常喜欢所有hexo主题中最喜欢的，除了目前的阅读体验（为了找个称心主题把hexo里的主题都看完了）。总结一下就是主页非常讨好人，文章的阅读缺会劝退用户粘性。而博客的核心就是文章，阅读体验也是重中之重。真心的希望您能采纳我的意见，期待您的回复。

**Comment by miiiku** [comment]
谢谢你提出的这几点意见，也看了你举例的那个网站模版，大概知道了你所说的效果且觉得也很有道理，目前的文章内容那块区域确实有点大，文字多了体验是挺不好的。

我会好好想一下怎么吧你所说的效果整合到现在到主题上，不过我本身设计水平较差😂，还有就是风格的问题，所以可能会导致修改时间较长或有可能采用其他显示效果，希望你继续保持关注。

最后：如果你对我的风格不满意到话也可以fork下来自己魔改～

**Comment by DRSalieri** [comment]
同感，这个主题的主界面非常好看，应该可以说是我看过所有主题中最合我胃口的一个，问了其他同学也都说好看，让人有想阅读的欲望。
但是一打开文章之后就有点劝退了。。。
我认为blog中的文章页面两侧是不是可以加一些什么东西？比如边框之类的。

**Comment by miiiku** [comment]
@DRSalieri  😂😂心酸的故事～，我个人也认为内容页面不是很好看，但是奈何没有设计感，想不出好看的设计，也一直是一个痛点，前段时间内容页稍微微调了下样式。

如果你有什么好的设计可以fork了魔改一下(哭泣
