### ISSUE TITLE
头像设置了无法显示

### ISSUE THREAD

**Issue by YaYiJiang** [miiiku/hexo-theme-flexblock#58]
佬，_config.yml文件中avatar设置了无法显示，路径正确

**Comment by miiiku** [comment]
看下路径问题呢，如果是cdn资源一般不会出问题，你是不是用的本地资源，url路径最好写绝对路径

**Comment by YaYiJiang** [comment]
佬，用的确实是本地资源，路径用的相对路径，我看你博客的头像都没有加载，是不是加载有问题

**Comment by YaYiJiang** [comment]
有没有QQ群啊佬

**Comment by miiiku** [comment]
路径没配对把，使用使用绝对路径呢。没有q群，只有个自己闲聊的小群，114663665

**Comment by seeleclover** [comment]
我找到原因了，是自定义友链的内容模板没改过来。

@YaYiJiang 你目前可以使用旧版本的友链数据添加方式来暂时解决这个问题：
```yaml
- { "name" : "", "link" : "", "describe" : "", "cover" : "" }
```

**Comment by seeleclover** [comment]
我提交了PR来解决这个问题，望采纳。 @miiiku

**Comment by seeleclover** [comment]
补充：
站点头像可以使用相对路径，放在 ./<Hexo站点目录>/source/links 目录下；
但为了后续的可维护性，图片资源建议都使用图床来存储，并在引用时使用绝对路径。

@YaYiJiang
