### ISSUE TITLE
希望新增显示“文章最后更新时间”的功能

### ISSUE THREAD

**Issue by seeleclover** [miiiku/hexo-theme-flexblock#62]
大概预览效果如下：
![image](https://user-images.githubusercontent.com/37256067/209323028-3548815d-ac9a-4c18-8871-f6dd1dce4a9e.png)

我观看了一些别人的Hexo主题，以及阅读了Hexo的官方文档对于 front-matter 参数的支持，发现有的博客主题是支持 updated 这个参数的。于是自己尝试写了一下这块的代码。
我想听听大佬对于这块功能的看法，如果大佬愿意收录，那我就提一个 Pull Request 过来。 @miiiku

**Comment by miiiku** [comment]
完全可以，加油，我看好你，不过我觉得要注意一点点就是如果没有更新过，就不展示更新时间，只有文章修改过再展示更新时间这样可能会好点，不然如果没有更新过的文章（指第一次发布）会出现更新时间跟发布时间一模一样的情况捏~
