### ISSUE TITLE
关于上传代码块问题

### ISSUE THREAD

**Issue by AlanYagn** [miiiku/hexo-theme-flexblock#67]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/113336169/230573111-192d548b-a8d5-45dc-bbcf-19b91303c2ca.png">
用vscode编辑的Java 代码，在上传后网页中的代码显示呈居中形式，请问是哪里出错了

**Comment by seeleclover** [comment]
请问你有使用 hexo-theme-flexblock 这个主题吗？是否有更换过代码块高亮的插件？

**Comment by AlanYagn** [comment]
没有，一切都是默认的

**Comment by miiiku** [comment]
你这个主题看起来好像不是flexblock啊
