### ISSUE TITLE
Adding background images to posts...

### ISSUE THREAD

**Issue by ShamalLakshan** [miiiku/hexo-theme-flexblock#69]
How to add background images to posts as in the screenshots?
![](https://github.com/miiiku/hexo-theme-flexblock/blob/master/screenshots/flex-block.png)

Tried different things in the post header but nothing worked out for me.

**Comment by miiiku** [comment]
Add a `cover` in the `Front Matter` of the `cover: [image url]`

`Front Matter` See [https://hexo.io/zh-cn/docs/front-matter](https://hexo.io/zh-cn/docs/front-matter)

**Comment by ShamalLakshan** [comment]
It worked, Thanks
