### ISSUE TITLE
对于添加了复制代码按键的代码块，在特殊情况下会随着超出代码块长度的文本移动

### ISSUE THREAD

**Issue by dangjinghao** [miiiku/hexo-theme-flexblock#71]
当`config.highlight.hljs`设置为false时，复制按键会随着较长的代码行移动
<img width="370" alt="image" src="https://github.com/miiiku/hexo-theme-flexblock/assets/53005337/16eff319-eb21-4f47-9e79-8970ea72fe29">

但是当hljs设置为false时行号也会一起移动，而此时highlightjs由于代码块的标签的class缺少hljs前缀默认无法正常渲染出关键字对应颜色，所以这或许并非严重问题？或许可以等待下次大改时顺便修复？

**Comment by miiiku** [comment]
[https://hexo.io/zh-cn/docs/syntax-highlight#hljs](https://hexo.io/zh-cn/docs/syntax-highlight#hljs)如果不开启`hljs`是无法匹配出对应的主题，这是正常的，至于没开启`hljs`导致的按钮会跟随移动，这个应该是没做处理，hexo在处理代码高亮这块自由度不够高，无法自定义渲染，不好控制代码块内的元素内容，没有针对每一种情况都做处理，目前建议使用`highlight `并开启`line_number `，`warp`和`hljs`。

等下次大更新的时候在考虑要不要用其他插件渲染markdown
