### ISSUE TITLE
希望添加行内数学公式支持

### ISSUE THREAD

**Issue by Ripening** [miiiku/hexo-theme-flexblock#90]
如题。希望添加这样的行内数学公式：`$ E = mc^2 $`。

---

（现在只支持独立数学公式：`$$ E = mc^2 $$`）

**Comment by dangjinghao** [comment]
你好，flexblock的数学公式渲染支持由mathjax提供，经过查询得知可以通过[此回答](https://tex.stackexchange.com/a/27656)设置。

但是我不知道这是否应该作为主题选项来单独配置。根据此回答，发现需要在加载mathjax之前进行配置才能满足需求。

是否应该采用更好的方式（例如在加载js库前和后阶段，添加自定义代码块来允许加载*可能*用于修改库配置的js代码）来实现更大的配置自由度？

**Comment by dangjinghao** [comment]
https://docs.mathjax.org/en/latest/basic/mathematics.html#tex-and-latex-input

https://docs.mathjax.org/en/latest/input/tex/delimiters.html#tex-delimiters

mathjax的相关文档

**Comment by Ripening** [comment]
感谢提供帮助！

~~可是我对相关知识几乎一无所知。~~ 目前我的解决方案是使用 [www.latexlive.com](www.latexlive.com) 输出为 MathML 代码再插入文章中。

**Comment by dangjinghao** [comment]
> 补充一下。采用上文中的方法后，行内公式在加载页面的时候公式会先显示成当没有修改 `layout.ejs` 且文章的 Front-matter 中 `mathjax` 为 `false` 时 `MathML` 公式会呈现的形状（如下图）。待页面完全加载后会变成上一回答图中的形状，这同时也是修改了 `layout.ejs` 后 Front-matter 中 `mathjax` 为 `false` 时独立数学公式（两个 `$$` 括起来的 LaTeX 公式）的形状。
> 
> 无论 Front-matter 中 `mathjax` 的值如何，都不影响行内公式的样式。
> 
> 描述有点绕请见谅……
> 
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/66284192/353469952-e6534ff2-a741-4663-bf1c-ea9f1808d27b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDU2NDgsIm5iZiI6MTcyMjM0NTM0OCwicGF0aCI6Ii82NjI4NDE5Mi8zNTM0Njk5NTItZTY1MzRmZjItYTc0MS00NjYzLWJmMWMtZWE5ZjE4MDhkMjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEzMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNmJiOWQyZDViZmNlYWQ0ODAwZTVkZTRlNTJmNWVhMDk2ZjZjYTEzNTcyOTlmZDYxN2YyMjkzMTQxNGJkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWSIez8cIPb6wMlRhfx5STuuqaIulPWHrr7hbOn6Azk">

 你提及的issue是在我添加mathjax功能之前产生的，此issue内容目前有些过时。

当设置`mathjax: true`时，实际上就是从jsdelivr cdn中加载mathjax库。当它为false时则不加载。

根据[文档](https://docs.mathjax.org/en/latest/web/start.html#configuring-mathjax)表示：配置启用$$标记行内数学公式的方式为：在[layout.ejs#L56](https://github.com/miiiku/hexo-theme-flexblock/blob/1e531b942675fe24b185451a33062844c8f4d148/layout/layout.ejs#L56)上写入
```
<script>
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  }
};
</script>
```
![image](https://github.com/user-attachments/assets/e588515e-15de-4796-8ded-81d019343781)

修改主题后可以直接使用$$设置行内公式，例如
![image](https://github.com/user-attachments/assets/2e30821c-59e8-4bf7-8ac0-214367a760dd)

你提及的issue可能由于时间问题，使用方法已和本主题采用的mathjax的版本使用方法相去甚远，建议按照我在上文的指引进行配置。这是根据我的步骤实现的效果
![image](https://github.com/user-attachments/assets/99bb59cd-74ce-44a7-b53f-cad49c2a4811)

**Comment by Ripening** [comment]
> > 补充一下。采用上文中的方法后，行内公式在加载页面的时候公式会先显示成当没有修改 `layout.ejs` 且文章的 Front-matter 中 `mathjax` 为 `false` 时 `MathML` 公式会呈现的形状（如下图）。待页面完全加载后会变成上一回答图中的形状，这同时也是修改了 `layout.ejs` 后 Front-matter 中 `mathjax` 为 `false` 时独立数学公式（两个 `$$` 括起来的 LaTeX 公式）的形状。
> > 无论 Front-matter 中 `mathjax` 的值如何，都不影响行内公式的样式。
> > 描述有点绕请见谅……
> > <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/66284192/353469952-e6534ff2-a741-4663-bf1c-ea9f1808d27b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDU2NDgsIm5iZiI6MTcyMjM0NTM0OCwicGF0aCI6Ii82NjI4NDE5Mi8zNTM0Njk5NTItZTY1MzRmZjItYTc0MS00NjYzLWJmMWMtZWE5ZjE4MDhkMjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEzMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNmJiOWQyZDViZmNlYWQ0ODAwZTVkZTRlNTJmNWVhMDk2ZjZjYTEzNTcyOTlmZDYxN2YyMjkzMTQxNGJkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWSIez8cIPb6wMlRhfx5STuuqaIulPWHrr7hbOn6Azk">
> 
> 你提及的issue是在我添加mathjax功能之前产生的，此issue内容目前有些过时。
> 
> 当设置`mathjax: true`时，实际上就是从jsdelivr cdn中加载mathjax库。当它为false时则不加载。
> 
> 根据[文档](https://docs.mathjax.org/en/latest/web/start.html#configuring-mathjax)表示：配置启用$$标记行内数学公式的方式为：在[layout.ejs#L56](https://github.com/miiiku/hexo-theme-flexblock/blob/1e531b942675fe24b185451a33062844c8f4d148/layout/layout.ejs#L56)上写入
> 
> ```
> <script>
> window.MathJax = {
>   tex: {
>     inlineMath: [['$', '$'], ['\\(', '\\)']]
>   }
> };
> </script>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/53005337/353494511-e588515e-15de-4796-8ded-81d019343781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTAyMTEsIm5iZiI6MTcyMjM0OTkxMSwicGF0aCI6Ii81MzAwNTMzNy8zNTM0OTQ1MTEtZTU4ODUxNWUtMTVkZS00Nzk2LThkZWQtODFkMDE5MzQzNzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0MzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOThhZmM1MTA5ZDI0YTkyZDhkMGEwZGU4ZGY4NGE4YzJjMzU0NmQyMTA4ODA2Mzg0ODZjZDk3OTUyZDNmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-zrcDl_5zxCeLP06qMIX1dwijXuSmrzmjinviGY6s7c)
> 
> 修改主题后可以直接使用$$设置行内公式，例如 ![image](https://private-user-images.githubusercontent.com/53005337/353492322-2e30821c-59e8-4bf7-8ac0-214367a760dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTAyMTEsIm5iZiI6MTcyMjM0OTkxMSwicGF0aCI6Ii81MzAwNTMzNy8zNTM0OTIzMjItMmUzMDgyMWMtNTllOC00YmY3LThhYzAtMjE0MzY3YTc2MGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0MzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTBjNDk5NmFlOWVlM2ZmNGY2MmM1YWZkMmVjNzFlYWFmZDQ2ZDViYzFjNTJjOWYyZDkzMWQ0YzdkYjNkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pg_BJmEic2ZHztSnXfG9H5Js5RAp66IxHl-D08no3v8)
> 
> 你提及的issue可能由于时间问题，使用方法已和本主题采用的mathjax的版本使用方法相去甚远，建议按照我在上文的指引进行配置。这是根据我的步骤实现的效果 ![image](https://private-user-images.githubusercontent.com/53005337/353497921-99bb59cd-74ce-44a7-b53f-cad49c2a4811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTAyMTEsIm5iZiI6MTcyMjM0OTkxMSwicGF0aCI6Ii81MzAwNTMzNy8zNTM0OTc5MjEtOTliYjU5Y2QtNzRjZS00NGE3LWI1M2YtY2FkNDljMmE0ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0MzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTQxNjdhZGFmZWQ0YTMyZTBmZGM4NjU5YzZjMzcxZjE1YTYxOWQ5ZDA3M2YzOWZjZjJkNzRjMDBjZTU4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZN_b4Pv9HNLz5Xs4j11pUy-zcbh4_H2fxGWGLU5un-4)

非常感谢，问题已成功解决！！
